### ISSUE TITLE
How is the consensus column derived?

### ISSUE THREAD

**Issue by SamWilsn** [raid-guild/indexed#98]
I noticed that there is a bit of ambiguity in how the "consensus" column is defined, or maybe I don't understand the space in enough depth.

For example, the Fuel Labs row is listed as PoW. From my understanding, there is no hashing or "work" of any kind in the Fuel protocol itself. Instead, block producers have to put up a "bond" in the Fuel contract which is returned after a period of time, if no fraud was detected in their produced block. That would make the system more like Proof-of-Stake.

You could make the argument that Fuel is indeed PoW because it relies on an Ethereum contract to handle on-chain computation. If that logic were consistently applied, Loopring should also be PoW, since it also relies on an on-chain Ethereum contract.

**Comment by gakonst** [comment]
In general, the methodology for populating this table is unclear. The features required to classify these inputs are many more than just "type, consensus, tx cost, max tps". Here's [one](https://eprint.iacr.org/2019/360.pdf) example of an SoK with categories that they investigated, and the corresponding [blogpost](https://s-tikhomirov.github.io/sok-off-the-chain-transactions/) (which arguably needs to be updated given progress since it was published.) Here's [another one](https://eprint.iacr.org/2019/1128.pdf) for x-chain communication (look for Table 1)

The methodology for adding an entry to the list should be made explicit, and the information shown should be expanded to include stuff like liveness requirements, EVM compatibility, on-chain vs off-chain footprint etc.

Also, the featured chains should prob not be present, if you want to be an objective resource! This is a great initiative, but curating such information needs to be more detailed to correctly communicate the tradeoff space. Otherwise, it becomes a marketing gimmick :/

(Apologies in advance if my tone seems off, this is meant in a as-constructive way as possible)

**Comment by chair28980** [comment]
@SamWilsn @gakonst 

Hi folks! Thank you for your feedback, this is exactly what I'm looking for.

This initial set of data was crowdsourced and is...all over the place. I'm working now to clean things up.

Re: Table data ambiguity and population methodology.

I agree. This is not an ideal state, @gakonst your references are perfect and I'll be looking at those today.

The methodology for adding an entry will become more clear as well.

![Screen Shot 2021-01-27 at 9 26 17 AM](https://user-images.githubusercontent.com/29414216/106005057-d4abab00-6081-11eb-9a39-5ed445fa2f6c.png)

This looks great!!!

I'm going to talk to the team about the Featured Chains point you bring up as well.

Again, thank you both and lets keep the conversation going, we aim to make this as useful as possible!
